# update notifications
notifications:
  email:
    on_success: never

# Enable C support
language: c

sudo: required

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  # add 32-bit support to docker-vm
  - export C_INCLUDE_PATH=/usr/include/$(gcc -print-multiarch)
  - sudo apt-get install gcc-multilib
  # real build
  - mkdir build
  - cd build
  - cmake .. && cmake --build . && ctest --output-on-failure

