# update notifications
notifications:
  email:
    on_success: never

# Enable C support
language: c

sudo: required

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - mkdir build
  - cd build
  - cmake .. && cmake --build . && ctest --output-on-failure
