#ifndef __XCPLIGHT_CONFIG_H
#define __XCPLIGHT_CONFIG_H

/** INCLUDES **/
#include <stdint.h>

/** CONFIG **/
#define XCPLIGHT_CFG_XTO_LENGTH 8

/** OPTIONS **/
//#define XCPLIGHT_CFG_ENABLE_CALPAG
//#define XCPLIGHT_CFG_ENABLE_DAQ
//#define XCPLIGHT_CFG_ENABLE_STIM
//#define XCPLIGHT_CFG_ENABLE_PGM

//#define XCPLIGHT_CFG_ENABLE_RESOURCE_PROTECTION

#endif // __XCPLIGHT_CONFIG_H

